const ShopActionsTypes = {
    FETCH_COLLECITONS_START: 'FETCH_COLLECITONS_START',
    FETCH_COLLECITONS_SUCCESS: 'FETCH_COLLECITONS_SUCCESS',
    FETCH_COLLECITONS_FAILURE: 'FETCH_COLLECITONS_SUCCESS',
};

export default ShopActionsTypes;